/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package marist.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Server service. Represents a row in the &quot;Marist_Server&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link marist.service.model.impl.ServerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link marist.service.model.impl.ServerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Server
 * @see marist.service.model.impl.ServerImpl
 * @see marist.service.model.impl.ServerModelImpl
 * @generated
 */
@ProviderType
public interface ServerModel extends BaseModel<Server>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a server model instance should use the {@link Server} interface instead.
	 */

	/**
	 * Returns the primary key of this server.
	 *
	 * @return the primary key of this server
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this server.
	 *
	 * @param primaryKey the primary key of this server
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this server.
	 *
	 * @return the uuid of this server
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this server.
	 *
	 * @param uuid the uuid of this server
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the server ID of this server.
	 *
	 * @return the server ID of this server
	 */
	public long getServerId();

	/**
	 * Sets the server ID of this server.
	 *
	 * @param serverId the server ID of this server
	 */
	public void setServerId(long serverId);

	/**
	 * Returns the group ID of this server.
	 *
	 * @return the group ID of this server
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this server.
	 *
	 * @param groupId the group ID of this server
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this server.
	 *
	 * @return the company ID of this server
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this server.
	 *
	 * @param companyId the company ID of this server
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this server.
	 *
	 * @return the user ID of this server
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this server.
	 *
	 * @param userId the user ID of this server
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this server.
	 *
	 * @return the user uuid of this server
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this server.
	 *
	 * @param userUuid the user uuid of this server
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this server.
	 *
	 * @return the user name of this server
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this server.
	 *
	 * @param userName the user name of this server
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this server.
	 *
	 * @return the create date of this server
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this server.
	 *
	 * @param createDate the create date of this server
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this server.
	 *
	 * @return the modified date of this server
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this server.
	 *
	 * @param modifiedDate the modified date of this server
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the distribution of this server.
	 *
	 * @return the distribution of this server
	 */
	@AutoEscape
	public String getDistribution();

	/**
	 * Sets the distribution of this server.
	 *
	 * @param distribution the distribution of this server
	 */
	public void setDistribution(String distribution);

	/**
	 * Returns the version of this server.
	 *
	 * @return the version of this server
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this server.
	 *
	 * @param version the version of this server
	 */
	public void setVersion(String version);

	/**
	 * Returns the vpn of this server.
	 *
	 * @return the vpn of this server
	 */
	public boolean getVpn();

	/**
	 * Returns <code>true</code> if this server is vpn.
	 *
	 * @return <code>true</code> if this server is vpn; <code>false</code> otherwise
	 */
	public boolean isVpn();

	/**
	 * Sets whether this server is vpn.
	 *
	 * @param vpn the vpn of this server
	 */
	public void setVpn(boolean vpn);

	/**
	 * Returns the memory of this server.
	 *
	 * @return the memory of this server
	 */
	public int getMemory();

	/**
	 * Sets the memory of this server.
	 *
	 * @param memory the memory of this server
	 */
	public void setMemory(int memory);

	/**
	 * Returns the disk of this server.
	 *
	 * @return the disk of this server
	 */
	public int getDisk();

	/**
	 * Sets the disk of this server.
	 *
	 * @param disk the disk of this server
	 */
	public void setDisk(int disk);

	/**
	 * Returns the cpu of this server.
	 *
	 * @return the cpu of this server
	 */
	@AutoEscape
	public String getCpu();

	/**
	 * Sets the cpu of this server.
	 *
	 * @param cpu the cpu of this server
	 */
	public void setCpu(String cpu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Server server);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Server> toCacheModel();

	@Override
	public Server toEscapedModel();

	@Override
	public Server toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}